apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-dev
  labels:
    app: {{ .Values.appName }}
    environment: dev
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
      environment: dev
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
        environment: dev
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
